version: "3.1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
  employee-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
